name: Deploy Knotris

on: push

jobs:
  build_game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Knotris Source Code
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
      
      - name: Print Starting
        run: echo "Starting Build!"

      - name: export game
        uses: firebelley/godot-export@v2.4.0
        with:
          # Defining all the required inputs
          # I used the mono version of Godot in this example
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_x11.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz
          relative_project_path: ./
          create_release: false
          generate_release_notes: false
          use_preset_export_path: true
          update_windows_icons: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Export Folder Contents
        run: ls ./docs/exports
