name: Deploy Knotris

on: push

jobs:
  build_game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Knotris Source Code
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: Print Base Ref  
          run: echo ${{github.base_ref}}
      - name: Print Head Ref  
          run: echo ${{github.head_ref}}
      - name: Print Ref  
          run: echo ${{github.ref}}
      - name: export game
        uses: firebelley/godot-export@v2.4.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_export_templates.tpz
          relative_project_path: ./
          create_release: false
          generate_release_notes: false
          use_preset_export_path: true
          update_windows_icons: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
